### ISSUE TITLE
Kaltura PHP 5.3 Library error

### ISSUE THREAD

**Issue by kkraju4u** [kaltura/php-api-examples#1]
Using Kaltura PHP 5.3 library in php 5.5

error: curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead 

file: Kaltura/Client/Base.php line no: 296

```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, 1);
if (count($files) > 0)
{
foreach($files as &$file)
$file = "@".$file; // let curl know its a file
curl_setopt($ch, CURLOPT_POSTFIELDS, array_merge($params, $files)); //ERROR HERE
}
```

Please also find the below attached screenshot.

![screenshot from 2014-06-28 02 47 24](https://cloud.githubusercontent.com/assets/2597640/3420261/693ddf2c-fea0-11e3-88c8-ef28871b66ae.png)

**Comment by afrogeex** [comment]
Hi Jess,

Can you please address the post above?

Rgds.

**Comment by zoharbabin** [comment]
@afrogeex and @kkraju4u - The client library is intended for PHP 5.3. PHP 5.5 is not yet supported in Kaltura.
From http://www.php.net/manual/en/function.curl-setopt.php - 
![screenshot 2014-06-28 10 15 57](https://cloud.githubusercontent.com/assets/150514/3420954/ccf36fc2-fece-11e3-83bf-f800ed6bfddc.png)

You're welcome to make the changes required and submit them as pull-request.

**Comment by kkraju4u** [comment]
Obviously I tried changing it. But it comes to some other error, which says field "fileData" missing! That's why I posted the issue here. Hope you are gonna help.

**Comment by zoharbabin** [comment]
@kkraju4u if you'd like to paste the modified code and error you've got, we'd be happy to take a look.
A small note of caution - PHP5.5 brought a number of backward breaking changes with it, so it may very well be that there will be more changes to make than using CURLFile.

**Comment by kkraju4u** [comment]
Here is the modified code

if (count($files) > 0)
        {
                    $file = (array) new \CURLFile($files['fileData:tmp_name'], $files['fileData:type'], $files['fileData:name']);
//          foreach($files as &$file)
//              $file = "@".$file; // let curl know its a file
//                            dd($files);
            curl_setopt($ch, CURLOPT_POSTFIELDS, array_merge($params, $file));
        }

and the error is Missing parameter "fileData" 

![screenshot from 2014-06-28 20 50 10](https://cloud.githubusercontent.com/assets/2597640/3421091/f05aae22-fed7-11e3-9ae3-55be25be47c3.png)

**Comment by zoharbabin** [comment]
When you var_dump $files, what do u see?

**Comment by kkraju4u** [comment]
array(5) { ["fileData:name"]=> string(22) "Nature_Break_Water.mp4" ["fileData:type"]=> string(9) "video/mp4" ["fileData:tmp_name"]=> string(14) "/tmp/phpORbudU" ["fileData:error"]=> string(1) "0" ["fileData:size"]=> string(6) "537395" }

**Comment by jessp01** [comment]
Hello,

You were actually very close to the solution:) 
here is a working example which also includes testing whether the version is 5.3.n or higher.

I would highly appreciate it if you can submit a pull request to:
https://github.com/kaltura/server/tree/IX-9.19.0/generator/sources/php5

```
                    if (count($files) > 0)
                    {
                            if (version_compare(phpversion(), '5.4.0', '<')) {
                                    foreach($files as &$file)
                                            $file = "@".$file; // let curl know its a file

                            }else{
                                    $files = array('fileData' => new CurlFile($files['fileData'], null,basename($files['fileData'] )));

                            }
                            curl_setopt($ch, CURLOPT_POSTFIELDS, array_merge($params, $files));
                    }
                    else
                    {
                            curl_setopt($ch, CURLOPT_POSTFIELDS, $opt);
                    }
```

Thanks,
